refactor(*): consolidate
discordjs/gh-discord-middleware pull request #7
Opened 2022-10-26 11:51 UTC by ckohen

Some of this code was quite redundant, especially when adding new packages / apps

This refactor should make it 1 line changes to add new packages / apps (excluding readme docs).

Additionally, in order to support the refactor, the split to apps was made here. It should otherwise be identical to the functionality before the refactor.

2022-10-26 12:01 UTC, Jiralite approved these changes

2022-11-01 22:14 UTC, kyranet requested changes

2022-11-01 22:14 UTC, kyranet commented on src/api/_lib/utils/webhooks.ts
> +export const OverideWebhooks: Partial<Record<AppName | PackageName, DiscordWebhooksTarget>> = {
```suggestion
export const OverrideWebhooks: Partial<Record<AppName | PackageName, DiscordWebhooksTarget>> = {
```

And update the references everywhere else.

2022-11-01 22:14 UTC, kyranet commented on src/api/_lib/handlers/push.ts
> +		for (const name of Object.values(AppName)) {
I noticed we do `Object.values(AppName)` and `Object.values(PackageName)` very frequently, can't we cache them under `AppNameValues` and `PackageNameValues`?

2022-11-01 22:14 UTC, kyranet commented on src/api/_lib/handlers/push.ts
> +			}
```suggestion
			const prefix = `apps/${name}/`;
			if (commit.added.some((file) => file.startsWith(prefix))) {
				targets.add(name);
			}
			if (commit.modified.some((file) => file.startsWith(prefix))) {
				targets.add(name);
			}
			if (commit.removed.some((file) => file.startsWith(prefix))) {
				targets.add(name);
			}
```

2022-11-01 22:14 UTC, kyranet commented on src/api/_lib/handlers/push.ts
> +			}
Same thing would apply to the loop below.

2022-11-20 10:19 UTC, kyranet requested changes

2022-11-20 10:19 UTC, kyranet commented on src/api/_lib/handlers/push.ts
> +		commit.modified.some((file) => file.startsWith(prefix) || commit.removed.some((file) => file.startsWith(prefix)))
You have one `)` in the wrong place.

2022-11-20 10:20 UTC, ckohen commented on src/api/_lib/handlers/push.ts
> +		commit.modified.some((file) => file.startsWith(prefix) || commit.removed.some((file) => file.startsWith(prefix)))
smh lint did me dirty

2022-11-20 10:41 UTC, kyranet approved these changes

2022-11-27 11:53 UTC, vladfrangu approved these changes

2022-11-28 01:50 UTC, merged